main/urls.py
from django.urls import path
from .views import Home, Portfolio, About, Contact, NotFound

app_name = "main"

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('contact/', Contact.as_view(), name="contact"),
    path('about/', About.as_view(), name="about"),
    path('Portfolio/', Portfolio.as_view(), name="work"),

]

tizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

main/models.py
from django.db import models

class Work(models.Model):
    work_name = models.CharField(max_length=100, verbose_name="نام نمونه کار")
    work_description = models.TextField(max_length=200, verbose_name="توضیح کوتاه در مورد نمونه کار", null=True)
    work_url = models.CharField(verbose_name="کد نمونه کار در آپارات", max_length=300)
    displayOnLandingPage = models.BooleanField(default=False, verbose_name="نمایش در صفحه اصلی")

    class Meta:
        verbose_name_plural = "نمونه کار ها"


class TeamMember(models.Model):
    member_name = models.CharField(max_length=100, verbose_name="نام عضو تیم")
    member_job = models.CharField(max_length=150, verbose_name="وظیفه در تیم")
    member_image = models.ImageField(verbose_name="تصویر عضو", null="True", upload_to="team/")

    class Meta:
        verbose_name_plural = "اعضای تیم"


class Corporation(models.Model):
    corp_name = models.CharField(max_length=100, verbose_name="نام سازمان", null="True")
    corp_image = models.ImageField(verbose_name="لوگوی سازمان", null="True", upload_to="corp/")

    class Meta:
        verbose_name_plural = "همکاری ها"

main/forms.py
from django import forms
from captcha.fields import CaptchaField, CaptchaTextInput

class EmailForm(forms.Form):
    name = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'نام و نام خانوادگی'}), error_messages={'required': 'لطفا نام خود را وارد کنید'})
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder': 'ایمیل (در جایی منتشر نخواهد شد)'}), error_messages={'required': 'لطفا ایمیل خود را وارد کنید', 'invalid': 'لطفا یک ایمیل معتبر وارد کنید'})
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'موضوع پیام'}), error_messages={'required': 'لطفا موضوع پیام خود را وارد کنید'})
    message = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'متن پیام'}), error_messages={'required': 'لطفا پیام خود را بنویسید'})

    captcha = CaptchaField(label=False, widget=CaptchaTextInput(attrs={'placeholder': 'لطفا متن تصویر را وارد کنید'}), error_messages={'required': 'لطفا متن تصویر را وارد کنید', 'invalid': 'متن تصویر صحیح وارد نشده است'})

main/views.py
from django.shortcuts import render
from django.views.generic import View
from main.models import TeamMember, Corporation, Work
from .forms import EmailForm

class Home(View):
    def get(self, request):
        corporates = Corporation.objects.all()
        works = Work.objects.filter(displayOnLandingPage=True)
        context = {
            'corporates': corporates,
            'works': works
        }
        return render(request, 'main/home.html', context)


class About(View):
    def get(self, request):
        team_members = TeamMember.objects.all()
        works = Work.objects.filter(displayOnLandingPage=True)
        context = {
            'team_members': team_members,
            'works': works
        }
        return render(request, 'main/about.html', context)


class Portfolio(View):
    def get(self, request):
        works = Work.objects.all()
        context = {
            'works': works
        }
        return render(request, 'main/portfolio.html', context)


class Contact(View):
    def get(self, request):
        form = EmailForm()
        context = {
            'form': form
        }
        return render(request, 'main/contact.html', context)

    def post(self, request):
        form = EmailForm(data= request.POST)
        if form.is_valid():
            context = {
                'form': request.POST
            }
            return render(request, 'main/contact.html', context)
        else:
            context = {
                'form': form,
                'errors': form.errors
            }
            return render(request, 'main/contact.html', context)


class NotFound(View):
    def get(self, request):
        return render(request, 'main/notFound.html')

main/templates/main/about.html
{% extends './base.html' %}

{% load static %}

{% block 'title' %}
درباره ما
{% endblock %}

{% block 'content' %}

<header class="about-page">
    <p class="intro">
        درباره ما
    </p>
</header>

<main class="about-page">

    <div class="about-section">
        <div class="about">
            <div class="description" data-aos="fade-left" data-aos-duration="2000" data-aos-delay="1000" data-aos-once="true">
                م ایپسوم یا طرح‌نما (به انگلیسی: Lorem ipsum) به متنی آزمایشی و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود. طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد
            </div>
        </div>
        <div class="tv">
            <div class="screen"></div>
            <img src="{% static 'files/big-tv.png' %}" alt="">
        </div>
    </div>

    <div class="service-work-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="work-section">
        <div class="work-intro intro">
            <p class="title" data-aos="fade" data-aos-duration="2000" data-aos-once="true">چندی از نمونه کار ها...</p>
            <p class="message" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                تیم تیزر همواره سعی بر ارائه بهترین تیزرهای تبلیغاتی، جهت موفقیت کسب و کار شما در هر کمپین تبلیغاتی‌ دارد.
            </p>
            <a href="{% url 'main:work' %}" class="all-works-desktop" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                مشاهده تمام نمونه کار ها
            </a>
        </div>
        <div class="top-darken"></div>
        <div class="works keep-scrolling">

            {% if True %}
                <div class="work">
                    <div id="79039686089"><script type="text/JavaScript" src="https://www.aparat.com/embed/0klxC?data[rnddiv]=79039686089&data[responsive]=yes"></script></div>
                </div>
                <div class="work">
                    <div id="10080156393"><script type="text/JavaScript" src="https://www.aparat.com/embed/NO5si?data[rnddiv]=10080156393&data[responsive]=yes"></script></div>
                </div>
                <div class="work">
                    <div id="87668251956"><script type="text/JavaScript" src="https://www.aparat.com/embed/i2rXT?data[rnddiv]=87668251956&data[responsive]=yes"></script></div>
                </div>
            {% else %}
                <p class="not-found-message">
                    نمونه کار‌ها به زودی به روزرسانی می‌شوند
                </p>
            {% endif %}


            
        </div>
        <div class="bottom-darken"></div>
        <a href="{% url 'main:work' %}" class="all-works-mobile" data-aos="fade" data-aos-duration="2000" data-aos-once="true"">
                مشاهده تمام نمونه کارها
        </a>
    </div>

    <div class="team-section">
        <div class="team-intro intro">
            <p class="title">
                 اعضای تیم
            </p>
        </div>
        <div class="team-members">
            <div class="member">
                <img src="{% static 'files/jack.jpg' %}" alt="" class="member-image">
                <p class="member-name">
                    جک ما
                </p>
                <p class="member-about">
                    انیماتور و سرپرست تیم
                </p>
            </div>
            <div class="member">
                <img src="{% static 'files/jack.jpg' %}" alt="" class="member-image">
                <p class="member-name">
                    جک ما
                </p>
                <p class="member-about">
                    انیماتور و سرپرست تیم
                </p>
            </div>
            <div class="member">
                <img src="{% static 'files/jack.jpg' %}" alt="" class="member-image">
                <p class="member-name">
                    جک ما
                </p>
                <p class="member-about">
                    انیماتور و سرپرست تیم
                </p>
            </div>
            <div class="member">
                <img src="{% static 'files/jack.jpg' %}" alt="" class="member-image">
                <p class="member-name">
                    جک ما
                </p>
                <p class="member-about">
                    انیماتور و سرپرست تیم
                </p>
            </div>

        </div>
    </div>

</main>

{% endblock %}

main/templates/main/home.html
{% extends './base.html' %}

{% block 'title' %}
خانه
{% endblock %}

{% block 'content' %}
<header class="home-page">
    <video autoplay muted loop id="myVideo">
        {% load static %}
        <source src="{% static 'files/header.mp4' %}" type="video/mp4">
    </video>

    <div class="header-introduction">
        <div class="content">
            <h1>TIZER</h1>
            <p>تیزرهای تبلیغاتی متفاوت را با ما تجربه کنید</p>
        </div>
    </div>
</header>


<main class="home-page">
    <div class="header-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="services-section">
        <div class="services">
            <div class="services-intro intro">
                <p class="title">
                    خدماتی که به شما ارائه می‌دیم...
                </p>
            </div>
            <div class="services-options" data-aos="fade-left" data-aos-duration="2000" data-aos-delay="1000" data-aos-once="true">
                <ul>
                    <li>تیزر های تبلیغاتی برای کسب و کار شما</li>
                    <div class="seperator"></div>
                    <li>مشاوره و طراحی استراتژی‌های تبلیغاتی</li>
                    <div class="seperator"></div>
                    <li>اشکال یابی و بهبود برنامه های تبلیغاتی</li>
                    <div class="seperator"></div>
                    <li>طراحی انواع پوستر و لوگو</li>
                    <div class="seperator"></div>
                    <li>ساخت انیمیشن</li>
                    <div class="seperator"></div>
                </ul>
            </div>
        </div>
        <div class="laptop">
            <div class="screen"></div>
            <img src="{% static 'files/laptop.png' %}" alt="">
        </div>
    </div>

    <div class="service-work-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="work-section">
        <div class="work-intro intro">
            <p class="title" data-aos="fade" data-aos-duration="2000" data-aos-once="true">چندی از نمونه کار ها...</p>
            <p class="message" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                تیم تیزر همواره سعی بر ارائه بهترین تیزرهای تبلیغاتی، جهت موفقیت کسب و کار شما در هر کمپین تبلیغاتی‌ دارد.
            </p>
            <a href="{% url 'main:work' %}" class="all-works-desktop" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                مشاهده تمام نمونه کار ها
            </a>
        </div>
        <div class="top-darken"></div>
        <div class="works keep-scrolling">

            {% if True %}
                <div class="work">
                    <div id="79039686089"><script type="text/JavaScript" src="https://www.aparat.com/embed/0klxC?data[rnddiv]=79039686089&data[responsive]=yes"></script></div>
                </div>
                <div class="work">
                    <div id="10080156393"><script type="text/JavaScript" src="https://www.aparat.com/embed/NO5si?data[rnddiv]=10080156393&data[responsive]=yes"></script></div>
                </div>
                <div class="work">
                    <div id="87668251956"><script type="text/JavaScript" src="https://www.aparat.com/embed/i2rXT?data[rnddiv]=87668251956&data[responsive]=yes"></script></div>
                </div>
            {% else %}
                <p class="not-found-message">
                    نمونه کار‌ها به زودی به روزرسانی می‌شوند
                </p>
            {% endif %}


            
        </div>
        <div class="bottom-darken"></div>
        <a href="{% url 'main:work' %}" class="all-works-mobile" data-aos="fade" data-aos-duration="2000" data-aos-once="true"">
                مشاهده تمام نمونه کارها
        </a>
    </div>

    <div class="corp-section">
        <div class="corp-intro intro">
            <p class="title">
                همکاری‌های ما
            </p>
        </div>
        <div class="corps">
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
            <div class="corp">
                <img src="{% static 'files/snapp.png' %}" alt="" class="corp-image">
            </div>
        </div>
    </div>

</main>

{% endblock %}

templates/main/about.html
{% extends './base.html' %}

{% load static %}

{% block 'title' %}
درباره ما
{% endblock %}

{% block 'content' %}

<header class="about-page">
    <p class="intro">
        درباره ما
    </p>
</header>

<main class="about-page">

    <div class="about-section">
        <div class="about">
            <div class="description" data-aos="fade-left" data-aos-duration="2000" data-aos-delay="1000" data-aos-once="true">
                م ایپسوم یا طرح‌نما (به انگلیسی: Lorem ipsum) به متنی آزمایشی و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود. طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد
            </div>
        </div>
        <div class="tv">
            <div class="screen"></div>
            <img src="{% static 'files/big-tv.png' %}" alt="">
        </div>
    </div>

    <div class="service-work-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="work-section">
        <div class="work-intro intro">
            <p class="title" data-aos="fade" data-aos-duration="2000" data-aos-once="true">چندی از نمونه کار ها...</p>
            <p class="message" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                تیم تیزر همواره سعی بر ارائه بهترین تیزرهای تبلیغاتی، جهت موفقیت کسب و کار شما در هر کمپین تبلیغاتی‌ دارد.
            </p>
            <a href="{% url 'main:work' %}" class="all-works-desktop" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                مشاهده تمام نمونه کار ها
            </a>
        </div>
        <div class="top-darken"></div>
        <div class="works keep-scrolling">

            {% if works %}
                {% for work in works %}
                    <div class="work">
                        {{ work.work_url |safe }}
                    </div>
                {% endfor %}
            {% else %}
                <p class="not-found-message">
                    نمونه کار‌ها به زودی به روزرسانی می‌شوند
                </p>
            {% endif %}


            
        </div>
        <div class="bottom-darken"></div>
        <a href="{% url 'main:work' %}" class="all-works-mobile" data-aos="fade" data-aos-duration="2000" data-aos-once="true"">
                مشاهده تمام نمونه کارها
        </a>
    </div>

    <div class="team-section">
        <div class="team-intro intro">
            <p class="title">
                 اعضای تیم
            </p>
        </div>
        <div class="team-members">
            {% if team_members %}
                {% for member in team_members %}
                <div class="member">
                    <img src="{% get_media_prefix %}{{ member.member_image }}" alt="" class="member-image">
                    <p class="member-name">
                        {{ member.member_name }}
                    </p>
                    <p class="member-about">
                        {{ member.member_job }}
                    </p>
                </div>
                {% endfor %}
            {% else %}
                <div class="not-found-warning">
                    به زودی اعضای تیم بروزرسانی می‌شوند
                </div>
            {% endif %}

        </div>
    </div>

</main>

{% endblock %}

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block 'title' %}{% endblock %}</title>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="{% static 'styles/css/main.css' %}">
</head>


<body>

  <div class="page-before-load">

  </div>

  <nav id="navbar">
      <button class="navbar-button">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
      </button>
      {% if request.path == "/" %}
      <div class="navigator">
          <div class="navigator-container">
            <div class="home-navigator navigator-button"></div>
            <div class="services-navigator navigator-button"></div>
            <div class="work-navigator navigator-button"></div>
            <div class="corp-navigator navigator-button"></div>
          </div>
      </div>
      {% endif %}
  </nav>

  <div class="menu">
    <div class="options">
      <div class="option">
        <a href="{% url 'main:home' %}" class="{% if request.path == '/' %}menu-active{% endif %}">
         خانه
        </a>
     </div>
     <div class="option">
          <a href="{% url 'main:about' %}" class="{% if request.path == '/about/' %}menu-active{% endif %}">
          درباره ما
          </a>
      </div>
      <div class="option">
        <a href="{% url 'main:work' %}" class="{% if request.path == '/work/' %}menu-active{% endif %}">
        پروژه ها
        </a>
      </div>
      <div class="option">
        <a href="{% url 'main:contact' %}" class="{% if request.path == '/contact/' %}menu-active{% endif %}">
        تماس با ما
        </a>
      </div>
    </div>
  </div>

    {% block 'content' %}

    {% endblock %}



    <footer>
      <div class="social-media">
        <a href="">
          <i class="fab fa-instagram"></i>
        </a>
        <a href=""><i class="fab fa-telegram-plane"></i></a>
        <a href=""><i class="fab fa-whatsapp"></i></a>
        <a href=""><i class="fab fa-linkedin-in"></i></a>
      </div>
      <div class="footer-quote">
          <div class="quote">تبلیغات خوب، باعث باهوش به نظر رسیدن کسب و کار است، اما تبلیغات عالی، باعث می‌شود مشتری حس هوشمندی داشته باشد!</div>
          <div class="author">"جو چرنوو - متخصص مارکتینگ در Pendo.io"</div>
      </div>
      <div class="footer-logo">
          TIZER
      </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    {% if request.path == "/" %}
      <script src="{% static 'styles/js/home.js' %}"></script>
    {% endif %}
    {% if request.path == "/about/" %}
      <script src="{% static 'styles/js/about.js' %}"></script>
    {% endif %}
    <script src="{% static 'styles/js/base.js' %}"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script src="https://kit.fontawesome.com/7b0dcc43a4.js" crossorigin="anonymous"></script>
    <script>
      AOS.init();
    </script>
</body>
</html>

templates/main/contact.html
{% extends './base.html' %}

{% block 'title' %}
ارتباط با ما
{% endblock %}

{% block 'content' %}
<header class="about-page">
    <p class="intro">
        ارتباط با ما
    </p>
</header>

<main class="contact-page">
    <div class="contact-choices">
        <div class="rapid-contact">
            <div class="rapid-contact-intro">
                ارتباط سریع
            </div>
            <form action="{% url 'main:contact' %}" method="post" novalidate>
                {% csrf_token %}

                {% for field in form %}
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="error">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
    
                <input type="submit" value="ارسال پیام">
            </form>
        </div>
        <div class="contact-information">
            <div class="contact-information-intro">
                اطلاعات ارتباطی
            </div>
            <div class="information">
                <div class="email">
                    <span>ایمیل:</span>
                    <span>navidproject283@gmail.com</span>
                </div>
                <div class="phone_number">
                    <span>شماره تماس:</span>
                    <span>09111111111</span>
                </div>
                <div class="social-media">
                    <span>شبکه‌های مجازی:</span>
                    <span>
                        <a href="">
                        <i class="fab fa-instagram"></i>
                      </a>
                      <a href=""><i class="fab fa-telegram-plane"></i></a>
                      <a href=""><i class="fab fa-whatsapp"></i></a>
                      <a href=""><i class="fab fa-linkedin-in"></i></a></span>
                </div>
            </div>
        </div>
    </div>

    <div class="address">
        <div class="address-info">
            آدرس ما
        </div>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3234.221600120421!2d50.96965375089903!3d35.843569428561565!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8dbf1fcae64fed%3A0xe6460055700c2bef!2sNika%20Mall!5e0!3m2!1sen!2sfr!4v1629205201095!5m2!1sen!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>
</main>
{% endblock %}

templates/main/home.html
{% extends './base.html' %}

{% block 'title' %}
خانه
{% endblock %}

{% block 'content' %}
<header class="home-page">
    <video autoplay muted loop id="myVideo">
        {% load static %}
        <source src="{% static 'files/header.mp4' %}" type="video/mp4">
    </video>

    <div class="header-introduction">
        <div class="content">
            <h1>TIZER</h1>
            <p>تیزرهای تبلیغاتی متفاوت را با ما تجربه کنید</p>
        </div>
    </div>
</header>


<main class="home-page">
    <div class="header-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="services-section">
        <div class="services">
            <div class="services-intro intro">
                <p class="title">
                    خدماتی که به شما ارائه می‌دیم...
                </p>
            </div>
            <div class="services-options" data-aos="fade-left" data-aos-duration="2000" data-aos-delay="1000" data-aos-once="true">
                <ul>
                    <li>تیزر های تبلیغاتی برای کسب و کار شما</li>
                    <div class="seperator"></div>
                    <li>مشاوره و طراحی استراتژی‌های تبلیغاتی</li>
                    <div class="seperator"></div>
                    <li>اشکال یابی و بهبود برنامه های تبلیغاتی</li>
                    <div class="seperator"></div>
                    <li>طراحی انواع پوستر و لوگو</li>
                    <div class="seperator"></div>
                    <li>ساخت انیمیشن</li>
                    <div class="seperator"></div>
                </ul>
            </div>
        </div>
        <div class="laptop">
            <div class="screen"></div>
            <img src="{% static 'files/laptop.png' %}" alt="">
        </div>
    </div>

    <div class="service-work-seperator">
        <div class="quote">
            اگر تصاویر هزاران کلمه ناگفته در خود دارند، ویدیو ها مانند یک کتابخانه هستند!
        </div>
        <div class="author">
           "سرینیواس نارایانان - سرپرست بخش هوش مصنوعی فیسبوک"
        </div>
    </div>

    <div class="work-section">
        <div class="work-intro intro">
            <p class="title" data-aos="fade" data-aos-duration="2000" data-aos-once="true">چندی از نمونه کار ها...</p>
            <p class="message" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                تیم تیزر همواره سعی بر ارائه بهترین تیزرهای تبلیغاتی، جهت موفقیت کسب و کار شما در هر کمپین تبلیغاتی‌ دارد.
            </p>
            <a href="{% url 'main:work' %}" class="all-works-desktop" data-aos="fade" data-aos-duration="2000" data-aos-once="true" data-aos-delay="1000">
                مشاهده تمام نمونه کار ها
            </a>
        </div>
        <div class="top-darken"></div>
        <div class="works keep-scrolling">

            {% if works %}
                {% for work in works %}
                    <div class="work">
                        {{ work.work_url |safe }}
                    </div>
                {% endfor %}
            {% else %}
                <p class="not-found-message">
                    نمونه کار‌ها به زودی به روزرسانی می‌شوند
                </p>
            {% endif %}


            
        </div>
        <div class="bottom-darken"></div>
        <a href="{% url 'main:work' %}" class="all-works-mobile" data-aos="fade" data-aos-duration="2000" data-aos-once="true"">
                مشاهده تمام نمونه کارها
        </a>
    </div>

    <div class="corp-section">
        <div class="corp-intro intro">
            <p class="title">
                همکاری‌های ما
            </p>
        </div>
        <div class="corps">
            <div class="corp">
                {% if corporates %}
                    {% for corporate in corporates %}
                    <img src="{% get_media_prefix %}{{ corporate.corp_image }}" alt="" class="corp-image">
                    {% endfor %}
                {% else %}
                    <div class="not-found-warning">
                        به زودی همکاری ها بروزرسانی می‌شوند
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

</main>

{% endblock %}

templates/main/notFound.html
{% extends './base.html' %}

{% block 'content' %}
<h1>
    404 Not found
</h1>
{% endblock %}